name: payflow
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  firebase_core: ^1.3.0
  google_sign_in: ^5.0.4
  google_sign_in_web: ^0.10.0
  shared_preferences: ^2.0.6
  google_ml_kit: ^0.6.0
  camera:
    git:
      url: https://github.com/camsim99/plugins.git
      path: packages/camera/camera
      ref: master
  image_picker: ^0.8.5+3
  font_awesome_flutter: ^10.1.0
  flutter_masked_text2: ^0.9.1
  animated_card: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/